plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'net.neoforged.gradle.userdev' version '7.0.170'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven { url = 'https://maven.theillusivec4.top/' }
    maven { url = 'https://maven.shedaniel.me/' }

    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
    }

    maven {
        name = 'GeckoLib'
        url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
    }

    maven {
        name = 'CurseMaven'
        url = 'https://cursemaven.com'
    }

    //noinspection GroovyAssignabilityCheck
    exclusiveContent {
        forRepository {
            maven {
                name = 'Modrinth'
                url = 'https://api.modrinth.com/maven'
            }
        }
        filter {
            includeGroup 'maven.modrinth'
        }
    }
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

//noinspection GroovyAssignabilityCheck
runs {
    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all',
                '--output', file('src/generated/resources/').getAbsolutePath(),
                '--existing', file('src/main/resources/').getAbsolutePath()
    }

    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

def arsNouveauJar = file('libs/ars_nouveau-1.21.1-5.13.0.jar')
def nuggetsJarName = 'nuggets-neoforge-1.21.1-1.1.0.48.jar'
def extractedNuggetsJar = layout.buildDirectory.file("extractedDependencies/${nuggetsJarName}")

tasks.register('extractArsNouveauNuggets') {
    inputs.file arsNouveauJar
    outputs.file extractedNuggetsJar

    doLast {
        copy {
            from zipTree(arsNouveauJar)
            include "META-INF/jarjar/${nuggetsJarName}"
            eachFile { details -> details.path = details.name }
            includeEmptyDirs = false
            into extractedNuggetsJar.get().asFile.parentFile
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly('top.theillusivec4.curios:curios-neoforge:9.5.1+1.21.1') { transitive = false }
    compileOnly('me.shedaniel.cloth:cloth-config-neoforge:15.0.140') { transitive = false }
    implementation "net.neoforged:neoforge:${neo_version}"
    compileOnly files(arsNouveauJar)
    compileOnly files(extractedNuggetsJar)
    compileOnly "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}"
    localRuntime files(arsNouveauJar)
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
    localRuntime "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    compileOnly "maven.modrinth:jade:${jade_version_id}"
    localRuntime "maven.modrinth:jade:${jade_version_id}"
    annotationProcessor "maven.modrinth:jade:${jade_version_id}"
}

tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [
            minecraft_version       : minecraft_version,
            minecraft_version_range : minecraft_version_range,
            neo_version             : neo_version,
            neo_version_range       : neo_version_range,
            loader_version_range    : loader_version_range,
            mod_id                  : mod_id,
            mod_name                : mod_name,
            mod_license             : mod_license,
            mod_version             : mod_version,
            mod_authors             : mod_authors,
            mod_description         : mod_description
    ]

    inputs.properties replaceProperties
    filesMatching('META-INF/neoforge.mods.toml') {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    dependsOn tasks.named('extractArsNouveauNuggets')
    options.encoding = 'UTF-8'
    options.annotationProcessorPath = configurations.annotationProcessor
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
